---
title: "Input format"
author: "Stef van Buuren (TNO), Annemieke Beuker (Allegro Sultum)"
date: "Nov 14, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Objective

This document describes the format of the input data accepted by JAMES. The specification

- closely follows the definition of the [Basisdataset JGZ 3.25 (2018)](https://www.ncj.nl/themadossiers/informatisering/basisdataset/);
- defines data objects;
- defines the actions taken by JAMES in case of incorrect, missing or out-of-range data;
- defines the error messages for informing the client.

## Generic object model

### EPremDossier Class

#### Object model 

EPremDossier  | Instance       | Class
------------- | -------------- | ------------ 
         ->   | Clientgegevens | EPremGroep
         ->   | Contactmomenten| EPremContactmoment

#### Syntax `C#`

`public class EPremDossier`

#### Public properties

Name            | Description                                   | Required
--------------- | --------------------------------------------- | -----
Clientgegevens  | Class with basic child data                   | Y
Contactmomenten | Class with data per visit                     | N
InstrumentCode  | Integer identifying the instrument            | Ignored
OrganisatieCode | Integer identifying the care organisation     | Y
Referentie      | String identifying the request                | N


### EPremGroep Class

#### Object model 

EPremGroep    | Instance       | Class
------------- | -------------- | ------------
         ->   | Elementen      | EPremElement
         ->   | Groepen        | EPremGroep

#### Syntax `C#`

`public class EPremGroep`

#### Public properties

Name            | Description                        | Required
--------------- | ---------------------------------- | --------
Elementen       | Class with BDS-elements            | Y
Groepen         | Class with groups of BDS-elements  | N

### EPremElement Class

#### Syntax `C#`

`public class EPremElement`

#### Public properties

Name               | Description                                   | Required
------------------ | --------------------------------------------- | ------
Bdsnummer          | Integer identifying the BDS-field             | Y
InternNummer       | Integer identifying internal field            | Ignored
Waarde             | Value of the BDS-field                        | Y
Waardeomschrijving | Descriptive label for value                   | Ignored

### EPremContactmoment Class

#### Object model 

EPremContactmoment  | Instance       | Class
------------------- | -------------- | ------------ 
               ->   | Elementen      | EPremElement 
               ->   | Groepen        | EPremGroep

#### Syntax `C#`

`public class EPremContactmoment : EPremGroep`

#### Public properties

Name            | Description                        | Required
--------------- | ---------------------------------- | --------
Elementen       | Class with BDS-elements            |    Y 
Groepen         | Class with groups of BDS-elements  |    N
Tijdstip        | Date of visit                      |    Y

## BDS-elements

| BDS   | Description             | Value  | Label                     | Required
| -----:|:----------------------- | ------:|:------------------------- | --------
| 19    | Sex of child            | "0"    | Unknown                   | Y
|       |                         | "1"    | Male                      |
|       |                         | "2"    | Female                    |
|       |                         | "3"    | Not specified             |
| 20    | Date of birth           | "yyyymmdd" | year-month-day        | Y
| 62    | Caretaker relation      | "01"   | biological father         | N
|       |                         | "02"   | biological mother         |
|       |                         | "03"   | male partner, stepfather  |
|       |                         | "04"   | female partner, stepmother|
|       |                         | "05"   | adoptive father           |
|       |                         | "06"   | adoptive mother           |
|       |                         | "07"   | foster father             |
|       |                         | "08"   | foster mother             |
|       |                         | "98"   | other                     |
| 63    | Caretaker date of birth | "yyyymmdd" | year-month-day        | N
| 66    | Caretaker education     | "01"   | no primary school         | N
|       |                         | "02"   | primary school, special ed|
|       |                         | "03"   | VSO-MLK/IVBO/VMBO-LWOO    |
|       |                         | "04"   | LBO/VBO/VMBO-BBL&KBL      |
|       |                         | "05"   | MAVO/VMBO-GL&TL           |
|       |                         | "06"   | MBO                       |
|       |                         | "07"   | HAVO/VWO                  |
|       |                         | "08"   | HBO/HTS/HEAO              |
|       |                         | "09"   | WO                        |
|       |                         | "98"   | Other                     |
|       |                         | "00"   | Unknown                   |
| 71    | Caretaker birth country | "dddd" | [4-digit code, Table 34](https://publicaties.rvig.nl/Landelijke_tabellen/Landelijke_tabellen_32_t_m_60_excl_tabel_35/Landelijke_Tabellen_32_t_m_60_in_csv_formaat)| N 
| 82    | Gestational age         | "ddd"  | in days                   | N
| 91    | Smoking during pregnancy| "1"    | yes                       | N
|       |                         | "2"    | no                        |
|       |                         | "99"   | unknown                   |
| 110   | Birth weight            | "dddd" | 3-4 digits, grammes       | N
| 235   | Length/height           | "dddd" | 3-4 digits, millimeters   | N
| 245   | Body weight             | "dddddd" | 3-6 digits, grammes     | N
| 252   | Head circumference      | "ddd"  | 2-3 digits, millimeters   | N
| 238   | Height biological mother| "dddd" | 3-4 digits, millimeters   | N
| 240   | Height biological father| "dddd" | 3-4 digits, millimeters   | N
| 510   | Passive smoking         | "01"   | No smoking in house       | N
|       |                         | "02"   | Never with child          |
|       |                         | "03"   | Not in last 7 days        |
|       |                         | "04"   | Yes                       |

## Error checking

Error checking of the JSON data occurs in three phases: 

1. PHASE 1: Check whether the JSON data are valid JSON. The process terminates
with an error message if the input JSON is not valid.

2. PHASE 2: Validate the JSON data against the JSON schema specification. The process terminates 
with an error if any required fields are missing. The process generates messages for data points 
that do not conform to the JSON schema, but continues.

3. PHASE 3: Check the range of the numeric data. The process generates messages for out-of-range
values, but continues using the specified values.

The default JSON schema in phase 2 is the built-in JSON schema `bds_schema_str.json`, a data format implementing a version that accepts strings as values for BDS-elements.




