#'@include class-individual.R
NULL

#'Cabinet class
#'
#'A collection of objects of class \code{individual} can be stored
#'into the class \code{cabinet} class.
#'The \code{cabinet} object can be generated by the \code{new("cabinet", ...)} and
#'\code{as(data, "cabinet")} functions.
#'The result is essentially a list of \code{individual} objects with an index.
#'Data of individual persons can be assessed by position by as list index
#'\code{`[[`} or by unique id by the vector index \code{`[`}.
#'@name cabinet-class
#'@rdname cabinet-class
#'@slot .Data A list of objects of class \code{individual}
#'@slot ids A number vector the indexes the (unique) individual \code{id}
#'@slot src Name of the source data
#'@slot created Creation date
#'@slot updated Update date
#'@aliases cabinet-class
#'@author Stef van Buuren 2016
#'@seealso \code{\link[=individual-class]{individual}}
#'@keywords classes
#'@examples
#'\dontrun{
#'# convert all 1933 children of SMOCC in `individual` objects
#'library("donordata")
#'all <- as(smocc, "cabinet")
#'
#'# same, but not relative to WHO references
#'all2 <- list2cabinet(smocc, libname = "who", prefix = "who2011", sub = "")
#'}
#'@export
setClass("cabinet",
         contains = "list",
         representation(
           ids     = "numeric",
           src     = "character",
           created = "POSIXct",
           updated = "POSIXct"
         ),
         prototype = list(
           new("individual"),
           src     = NA_character_,
           created = as.POSIXct(Sys.Date()),
           updated = as.POSIXct(Sys.Date())
           )
)

## as() reads the data structure as used in the
## donordata package, and transforms it into a cabinet object.
setAs("list", "cabinet", function(from) list2cabinet(from))

list2cabinet <- function(from, ...) {
  if (length(from) != 3) stop("Data type of unrecognised")
  ids <- from[[2]]$id
  individuals <- vector("list", length(ids))
  for (i in seq_along(individuals))
    individuals[[i]] <- donordata.to.individual(id = ids[i],
                                        src = from, ...)
  class(individuals) <- "cabinet"
  return(individuals)
}


#' Extract individuals from cabinet
#'
#'@param x An object of class \code{cabinet}
#'@param i Index vector
setMethod("[", signature(x = "cabinet", i = "ANY"),
          function (x, i) {
            individuals <- vector("list", length(i))
            for (j in seq_along(individuals))
              individuals[[j]] <- x[[j]]
            class(individuals) <- "cabinet"
            return(individuals)
          }
)



